name: Publish Docker images

on:
  pull_request:
  push:
    # run only against tags
    tags:
    - 'v*'

permissions:
  # contents: write
  packages: write
  # issues: write
  # id-token: write

jobs:
  imagepublisher:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
